### PR TITLE
Fix/layers not showing if not in key

### LINKED ISSUE #74: Adding a key hides layers
Without a key all layers are shown. However, when a key is specified only the layers that have corresponding entries in the key config are shown, all others are hidden. Instead all layers without key entries should default to being shown.

### PR DESCRIPTION
**Pull request by markstuart**
If a key is defined but not all layers are listed in the config, the unlisted layers were getting created but then hidden.

Fixes #74

### CODE REVIEW

**Comment by markstuart** [comment]
WAT

**Comment by digitalsadhu** [comment]
:+1: very nice (ala screenhero)

**Comment by digitalsadhu** [comment]
> @markstuart is a bad ass guitarist
> WAT

Just a weird way of paying you a compliment

**Comment by markstuart** [comment]
I usually figure it's just a weird way of <insert last thing you did here> whenever I don't quite grok you @digitalsadhu

**Comment by digitalsadhu** [comment]
@markstuart You can't use `<` and `>` in your comment without escaping them.

**Comment by markstuart** [comment]
Yes, so I see. Also can't edit messages in mobile view

**Comment by digitalsadhu** [comment]
Fixed it for you. You can buy me a beer later

**Pull request merged**
