### PR TITLE
Fix/es6 transpilation

### PR DESCRIPTION
**Pull request by digitalsadhu**
Changes to package.json
- Clean up unused dependencies
- Replace traceur with 6to5
- Add browserify transforms
- Fix dependencies

Changes to testem setup
- Replace traceur with 6to5

### CODE REVIEW

**Comment by digitalsadhu** [comment]
@markstuart @matt-in-a-hat Review pls when you get a chance

**Comment by markstuart** [comment]
What was your reasoning for fixed dependencies?

**Comment by digitalsadhu** [comment]
My thinking was that explicit updates means you go through once in a while update all the dependencies, run tests, commit and publish a new version. Means you are forced to be more purposeful with updates. I left dev dependencies dynamic. 


What do you think?

**Comment by markstuart** [comment]
I actually like this. Probably means we don't need to shrink wrap before releases. We should probably let our contributors know so that they don't worry about the shrink wrap file.
Do you want remove the file in this PR?

**Comment by digitalsadhu** [comment]
Can do. Thinking about it, maybe we should fix the dev deps as well?

**Comment by markstuart** [comment]
Yep, sounds good, keep the contributors test libs in line.

**Comment by markstuart** [comment]
@digitalsadhu, take a look at this when you get a chance please. Lets get this live!

**Comment by digitalsadhu** [comment]
:+1:

**Pull request merged**
