### PR TITLE
Pulls/key templating

### PR DESCRIPTION
**Pull request by benmanu**
Changing key templating to use config defined handlebars templates, and exposing the key on the mappy object.

### CODE REVIEW

**Comment by digitalsadhu** [comment]
@benmanu @flashbackzoo I like the ability to define custom key templating but I think it should probably be optional. 

Perhaps keep the loading of the existing template and then check if the user has defined the correct keys in config and use those if so.

**Comment by benmanu** [comment]
@digitalsadhu I've done some further work around setting a default template, and adding some more details to the readme for the key config. Just getting my head around the testing side of it so will push that through once I have it up and running smoothly.

**Comment by digitalsadhu** [comment]
@benmanu nice! Thanks man

**Comment by benmanu** [comment]
@digitalsadhu I've fixed up the broken key tests and added a custom template test to key.spec. If you could check the coverage is sufficient that would be awesome

**Comment by digitalsadhu** [comment]
@benmanu Would you mind rebasing the latest changes from the main repo onto you branch and re-pushing? It's been a while since the original PR came in and its gotten quite far out of date in the previous days merge chaos.

Not sure what your git practices are but we always rebase latest master onto a feature branch before merging it onto master so that we get a nice clean readable history. This means we always have to force push our branches back up after rebase which some people don't like...

**Comment by benmanu** [comment]
@digitalsadhu I've managed to rebase the changes onto master, there wasn't too many conflicts, a few test fixes but looking all good.

**Comment by digitalsadhu** [comment]
Awesome @benmanu will merge in tonight

**Comment by digitalsadhu** [comment]
Fixed in #87 
Had to do a final rebase to account for some changes made earlier today

**Pull request closed without merging**
